// 分饼干问题，贪心算法
mod find_content_children;
// 摆动序列
mod wiggle_max_length;
// 最大子序和
mod max_sub_array;
// 买卖股票
mod max_profit;
// 跳跃问题
mod can_jump;
// 最少跳跃问题
mod least_jump;
// K次取反最大值和问题
mod largest_sum_after_k_negations;
// 加油站问题
mod can_complete_circuit;
// 发糖问题
mod candy;
// 柠檬水找零
mod lemonade_change;
// 根据身高重新列队
mod reconstruct_queue;
// 射气球问题
mod find_min_arrow_shots;
// 无重叠区间问题
mod erase_overlap_intervals;
// 划分字母区间
mod partition_labels;
// 合并重叠区间
mod merge;
// 单调递增的数字
mod monotone_increasing_digits;
// 监控二叉树（TreeNode未实现，暂时不能跑）
mod min_camera_cover;
